deepseek_chat:
  class: OpenAIModel
  model_name: deepseek-chat 
  api_key: ${DEEPSEEK_API_KEY} 
  base_url: https://api.deepseek.com/v1
  temperature: 1.0

deepseek_reasoner:
  class: OpenAIModel 
  model_name: deepseek-reasoner 
  api_key: ${DEEPSEEK_API_KEY} 
  base_url: https://api.deepseek.com/v1 
  temperature: 1.0

gpt_4o:
  class: OpenAIModel
  model_name: gpt-4o
  api_key: ${OPENAI_API_KEY}
  base_url: https://api.openai.com/v1 
  temperature: 1.0

azure_openai_example:
  class: AzureOpenAIModel
  model_name: ${AZURE_OPENAI_MODEL}
  api_key: ${OPENAI_API_KEY}
  api_version: ${AZURE_OPENAI_API_VERSION}
  azure_endpoint: ${AZURE_ENDPOINT}
  temperature: 1.0


grok_4_offline:
  class: OpenAIModel
  model_name: grok-4
  api_key: ${XAI_API_KEY}
  base_url: https://api.x.ai/v1
  temperature: 1.0 
  # search_parameters:
  #   mode: "off"
  

naturelm:
  class: vllmModel
  model_name: microsoft/NatureLM-8x7B-Inst
  device: cuda
  temperature: 1.0
  
llama3_70B:
  class: vllmModel
  model_name: meta-llama/Llama-3.3-70B-Instruct
  device: cuda
  temperature: 1.0
  
qwen3_06B:
  class: vllmModel
  model_name: Qwen/Qwen3-0.6B
  device: cuda
  temperature: 1.0
  
qwen3_1_7B:
  class: vllmModel
  model_name: Qwen/Qwen3-1.7B
  device: cuda
  temperature: 1.0
  
qwen3_4B:
  class: vllmModel
  model_name: Qwen/Qwen3-4B
  device: cuda
  temperature: 1.0
  
qwen3_8B:
  class: vllmModel
  model_name: Qwen/Qwen3-8B
  device: cuda
  temperature: 1.0

qwen3_14B:
  class: vllmModel
  model_name: Qwen/Qwen3-14B
  device: cuda
  temperature: 1.0

qwen3_32B:
  class: vllmModel
  model_name: Qwen/Qwen3-32B
  device: cuda
  temperature: 1.0

# TODO: under development
agentom:
  class: GoogleADKModel  # Matches the class name in __init__.py
  model_name: Agentom
  app_name: agentom
  agent_url: http://127.0.0.1:8000  # Custom parameter defined in __init__